### ISSUE TITLE
Search bar / errors

### ISSUE THREAD

**Issue by aldohunicef** [unicef/etools-issues#152]
VIDEO PROOF AS EVIDENCE

Search bar has so many inconsistencies for Trips. 
Scenario 1) If user searches "traveler name" then it will appear only in certain cases. Not every traveler with active trips is showing up on the results. 
Scenario 2) If user inserts "Panchalingam" then the first results will come OK but if after that user needs to do a second search action - Let's say "Mohamed" then it will repeat the same results  for "Panchalingam", so it will show travels for "Panchalingam" again and not for the second name inserted. 
Scenario 3) User will do a hard reset and still the issue is showing up, then it will take 25 seconds to refresh but in Sierra Leone this might take up to 3 mins.

**Comment by torbent** [comment]
@anusenan @aldohunicef we are not sure this is a bug. We search in all fields for users, so if Panchalingam is a supervisor for Mohamed, all mohameds trips that Panchalingam was supervisor for also is shown. This is our only explanation we can reproduce.  And we believe this is correct behaviour. If not, please advise.

**Comment by torbent** [comment]
@anusenan @aldohunicef Would like to know how to proceed. Is this behaviour still up for debate, or is it accepted?

**Comment by kasfaw** [comment]
@torbent an update on this. We were able to reproduce this bug for users that have middle names like "Kidus Fisaha Asfaw". Since the middle name is captured as part of the first name field (First: Kidus Fisaha and Last: Asfaw)

In this scenario, my name only shows up success fully in the search result if i type "Kidus Fisaha". Nothing shows up if I search for "Kidus".

I believe this means that the search box is showing only EXACT matches. We would need it to show partial matches as well.

**Comment by janpanchalingam1** [comment]
Pass
