### ISSUE TITLE
DSA Areas missing - Kenya

### ISSUE THREAD

**Issue by aldohunicef** [unicef/etools-issues#154]
the full list of DSA area is not being populated so users can't calculate or plan trips to certain locations

**Comment by kasfaw** [comment]
@aldohunicef can you please provide more details on which specific DSA area is missing?

**Comment by janpanchalingam1** [comment]
@aldohunicef @kasfaw From: Monica Ondijo
Sent: Monday, March 20, 2017 2:04 PM
To: Nono Louise Harhoff <nlharhoff@unicef.org>; Elijah Asadhi <easadhi@unicef.org>
Subject: RE: eTools - issues from Kenya

Dear Nono,
Regarding WBS, there is actually no problem from the cases I have handled today, quite a number. The issue is colleagues are putting the WBS up to activity level which is wrong. We should capture up to the output level and with that They can pick the Grant .
The other new issue that I am going to raise shortly is that when we pick Programmatic Visit, select partner, the section for results is blank/no list of results
Best Regards
__________________
Monica Ondijo

I have asked Nono to send me any screenshots of missing information (if there is any) but this seems to be a training issue.

**Comment by janpanchalingam1** [comment]
DSA area missing is Kisumu (Acacia Premier)

**Comment by kasfaw** [comment]
@aldohunicef its been added.

**Comment by janpanchalingam1** [comment]
![image](https://cloud.githubusercontent.com/assets/26144740/24758210/af7e1b68-1aaf-11e7-805d-b1e080c8877b.png)

**Comment by janpanchalingam1** [comment]
DSA is not showing for Kenya in staging

**Comment by anusenan** [comment]
@robertavram @torbent  - The DSA area dropdown is populating in production but not in staging. Can you please check and clarify this?

**Comment by anusenan** [comment]
@robertavram @torbent any update on this?

**Comment by robertavram** [comment]
@anusenan this is most likely a data issue... we'll put the prod data in staging on Thursday.. let's see if that fixes it.
