### ISSUE TITLE
Modification to Certify Action

### ISSUE THREAD

**Issue by kasfaw** [unicef/etools-issues#186]
1. Change the action name "Certify" to "Finalize"
2. On Certify, execute the send payment workflow

**Comment by paragonHex** [comment]
@simon-the-sloth Please don't forget about the backend part of this!

**Comment by simon-the-sloth** [comment]
Invoices are generated here too.

**Comment by janpanchalingam1** [comment]
Initial test could not be completed because cost assignment was missing for users which were UNICEF users. Once retested as a finance focal point, was able to confirm that action name was changed from certify to finalize (see print screen 186.1). Need to change the pop-up box wording from Certified to Finalized. (see print screen 186.2)

**Comment by janpanchalingam1** [comment]
186.1 Screenshot:
![186 1 cerftify to finalize](https://cloud.githubusercontent.com/assets/26144740/24832200/53947714-1c78-11e7-9e74-c4dfe1b23fe1.png)
186.2 Screenshot:
![186 2 cerfity to finalize](https://cloud.githubusercontent.com/assets/26144740/24832201/57c5868e-1c78-11e7-8634-8a66a5a294f5.png)
