### ISSUE TITLE
Map Dashboard!!

### ISSUE THREAD

**Issue by anusenan** [unicef/etools-issues#20]
According to wire frames, this should include mapping according to PD/SSFA and Trip Activities

**Comment by marko911** [comment]
Some further details about this perhaps ?

**Comment by anusenan** [comment]
@mpawlowski85 _please help_

**Comment by mpawlowski85** [comment]
@marko911 @anusenan 
Here are some wireframes: 
https://projects.invisionapp.com/share/MD9LN1GJB#/screens/210174707 
Do you have any specific questions about this? This is one of the features that the dashboard should have. I am happy to dig out further details if you need anything specific. Please let me know.

**Comment by kasfaw** [comment]
@marko911 just to add to what marcin said. we would like a similar display of Trip Activities and filter by type, partner, partnership, and result

**Comment by marko911** [comment]
@kasfaw so two maps then ? both on same page ?

**Comment by kasfaw** [comment]
@marko911 if possible, yes. the thought was to have a toggle button of sorts that allowed you to go from seeing between trips and partnerships.

**Comment by evrimm** [comment]
@kasfaw I think it is more intuitive to have the trips map under Trips tab, and partnerships tab under Partnerships tab instead of having similar info spread over 3 different tabs. I can revise the screens accordingly. I need to show @marko911 Trips map anyway.

**Comment by evrimm** [comment]
Testing Results
Errors:
- Filters don't seem to work properly. Take a look at the screenshots. Screenshot 1: When show active toggle is on, take a look at the amount of markers on the map. Screenshot 2: "Field operations" sectors filter is added, now there are more markers because it's not filtered correctly.  Screenshot 3: Shows when clicked on one of the markers when "Field operations" is the selected filter, as you can see this location has no partnerships linked to this sector.   Screenshot 4: Shows the what seems to be the correct display after "Field Operations".

Filters: 
- Add Filter button sometimes doesn't work.
- There shouldn't be a "Show all active" toggle, as there is already a filter for "Status". 

Modal:
- Modal should be scrollable if the contents are longer. Currently they overflow. 
- The title of the modal which is the location name, should be followed by P-code in parentheses, not the location type.
- The blue text which is the PD ref. number should open the PD overview page in a new tab.

IE: 
- The map tiles don't load complete, can't see the whole map
- The map doesn't focus on the country
Further testing couldn't be done because of the above.

**Comment by evrimm** [comment]
![screenshot 1](https://cloud.githubusercontent.com/assets/1585349/25855623/b5f45e10-34a1-11e7-90cb-3e8f26d57755.png)
![screenshot 2](https://cloud.githubusercontent.com/assets/1585349/25855621/b4e650b4-34a1-11e7-993c-c420cdbf88ab.png)
![screenshot 3](https://cloud.githubusercontent.com/assets/1585349/25855620/b4e599f8-34a1-11e7-853e-ef3a32034f56.png)
![screenshot 4](https://cloud.githubusercontent.com/assets/1585349/25855622/b4f001ae-34a1-11e7-8cc0-b3acb464230a.png)

**Comment by marko911** [comment]
@evrimm I was not able to recreate the issue of the filters dropdown not working properly on any other machine except yours. Might need to work on your machine to dig into the problem.

**Comment by evrimm** [comment]
@marko911 
Current behavior is when user clicks on map tab, they don't see a map because it only loads upon selecting a filter. 
Expected behavior: Map loads and centers to the selected country when user click on map tab without having to select filters
