### ISSUE TITLE
FE Mandatory Programmatic Visits in Partner Overview displays incorrect values.

### ISSUE THREAD

**Issue by robertavram** [unicef/etools-issues#234]
See issue #177

FE will need to wait for api to be done

**Comment by robertavram** [comment]
API should be in staging.. this is ready for development

**Comment by mpawlowski85** [comment]
Failed - The record shows incorrect number of Audit  M.R. – as soon as 1 audit report is added, the M.R. changes to 0.

**Comment by adi130987** [comment]
@robertavram, @mpawlowski85, @daniel-tabarcea I'm not sure I understand the issue.
Isn't this related to https://github.com/unicef/etools-issues/issues/198 (already in develop) ?

**Comment by mpawlowski85** [comment]
Hi @adi130987 
most of the issue is solved, but for Audit. 
The Audit column displays Mandaroty Requirement (M.R.) and Done. Currently when there the system calculates that there is an audit requirement, the M.R. column shows 1. Once an audit report is uploaded (in another field in the system), the Done column shows 1, but at the same time the M.R goes down to 0. So here is the issue:  once the M.R. is 1 is should not change.

@ntrncic if you have anything else to add, please let me know.

**Comment by robertavram** [comment]
@adi130987 no worries about this.. it's a backend issue
