### ISSUE TITLE
Partner Authorized Officers

### ISSUE THREAD

**Issue by anusenan** [unicef/etools-issues#28]
eTools(3.9.5) does not behave as it should. This field picks up the list of partner authorized officers from eTools (2.3.1). However, if amendment to a PCA is added and the amendment type is "Change Authorized Officer", eTools(3.9.5) does not pick up on the new Authorized officer - the old ones are still displayed.

**Comment by ntrncic** [comment]
must do a hard refresh for new officer to show up i the dropdown

**Comment by robertavram** [comment]
@adi130987

**Comment by anusenan** [comment]
@robertavram if you are moving issues back to earlier stages/columns - can you please leave a comment as to why its pushed back?

**Comment by adi130987** [comment]
fixed by version v1.0.35 of esmm dropdown.

**Comment by mpawlowski85** [comment]
The Issue was tasted and failed. Additional feedback: 
At the moment, when you add amendment to a PCA that introduces a new Partner Authorized Officer, this change is not reflected on the PD page for the PDs that are linked to the PCA. 
The desired sequence of events is (Assuming there is an Active PCA):
1. Add new Staff Member to the Partner record
2. Amend an existing PCA to include the New Partner Staff Member as the Authorized Officer for that PCA. 
3. The New Staff Member appears in the PD screen field "Signed by UNICEF" for all PDs that are associated with that PCA that are in Draft and all future PDs. 
The issue was raised to mitigate step 3 that does not work and it still does not seem to work.

**Comment by adi130987** [comment]
@mpawlowski85 I think there is a misunderstanding here:  PD screen field "Signed by UNICEF" has nothing to do with Staff Members or Authorized Officers. "Signed by UNICEF" field only display the UNICEF users from group 'Senior Management'.

PD "Signed By Partner Authorized Officer" field reflects the changes made for in steps 1 and 2.

**Comment by mpawlowski85** [comment]
@adi130987 Sorry - I have now edited my comment. 
I meant "Signed by Partner Authorized Officer" field. Please re-read the comments now. I am happy to answer any further questions.

**Comment by adi130987** [comment]
@mpawlowski85 I checked this today and PD "Signed By Partner Authorized Officer" field reflects the changes made for in steps 1 and 2. I did the same steps you described and found no issue.

**Comment by mpawlowski85** [comment]
The issue was discussed with Adrian over the phone and the specifics were discussed. 
Adrian thinks that this will be a backend fix. He will discuss it with Rob in the next few days.

**Comment by adi130987** [comment]
@robertavram, @ntrncic, yesterday I had a call with @mpawlowski85 and we clarified the issue. 
Right now you have to manually add the officer selected in agreement amendment type to the agreement authorized partners list(Partner Authorized Officers field). We could automate this as a change request on backend at save.
![partner_authorized_officers](https://cloud.githubusercontent.com/assets/1955740/25035142/67a8572c-20f4-11e7-8715-a495bac3f0ec.png)

It can be done on frontend too, but this is more like a backend change, it's easier to be done on backend side.

What are your thoughts on this?

**Comment by robertavram** [comment]
Removing this from Ondeck since specs are changing around amendments
