### ISSUE TITLE
Partner Contact List

### ISSUE THREAD

**Issue by mpawlowski85** [unicef/etools-issues#294]
Not all fields mandatory: “name” (fist, last); “title” and email or telephone (not both).

**Comment by adi130987** [comment]
Changes done here: https://github.com/unicef/etools-partnership-management/pull/261

@robertavram, @ntrncic we need backend changes for this as the email address can not be null.

**Comment by mpawlowski85** [comment]
Browser: Chrome
Workspace: Philippines
Failing this card because
1) While adding a new partner contact I added all details except email id and clicked on Save. Got the following error message: •Field staff_members(email) - This field may not be blank.
2)Although while adding a new partner contact with all details except phone number the system allowed me to save the contact details

**Comment by adi130987** [comment]
@mpawlowski85 just one of phone and email fields are required, not both, as requested in this issue. This `Field staff_members(email) - This field may not be blank` message should be changed from backend side.

**Comment by robertavram** [comment]
@mpawlowski85 I believe we spoke about this requirement and we ended up on the conclusion that we need a unique email for each staff member / country office in order to insure a unique identity for these members. If we want a separate contact list (not entities that will be available to choose as document signatories) we should discuss as part of a new requirement...

can you please close this issue when you have a chance?

**Comment by mpawlowski85** [comment]
Yup - this is correct. We landed on the unique email.
