### ISSUE TITLE
Validation inconsictency for intervention

### ISSUE THREAD

**Issue by acory** [unicef/etools-issues#297]
Environment: DEV
Got to an intervention with status Active - Save
Go to Interventions list 
Create new intervention - To save it you are required to enter sector location and partner focal point and unicef focal points- Save it
Go to interventions list
Create new intervention
You can save it without entering sector location, partner focal points or Unicef focal points

**Comment by roxanavlad** [comment]
fail
I can still reproduce the issue described in the task

**Comment by adi130987** [comment]
"You can save it without entering sector location, partner focal points or Unicef focal points" this is because some fields are not required to create a new intervention. Some intervention fields(like sector locations, partner and unicef focal points) are required only if the intervention has the status `active` or `implemented`.

I think this issue was related to the fact validation error messages shown on saving an intervention with invalid fields were not reset after you open new intervention page. @acory can you confirm?

**Comment by roxanavlad** [comment]
@adi130987 , @acory , I can confirm that when adding a new intervention the fields(like sector locations, partner and unicef focal points) are not mandatory. 
if this is the expected functionality, then the task has passed UI testing.

**Comment by acory** [comment]
Yes, the fields are not mandatory when creating a new intervention
