### ISSUE TITLE
Offices and section in list view showing as N.A.

### ISSUE THREAD

**Issue by janpanchalingam1** [unicef/etools-issues#326]

**Comment by janpanchalingam1** [comment]
In Jordan, IE: 
![image](https://cloud.githubusercontent.com/assets/26144740/25537410/5b21478e-2c0c-11e7-9a5f-0068b106198d.png)

**Comment by janpanchalingam1** [comment]
In Kyrgyzstan Chrome and IE
![image](https://cloud.githubusercontent.com/assets/26144740/25822421/93770a68-3406-11e7-919c-8f478ae5594d.png)

**Comment by lordfuoco** [comment]
@ilcsik this is a ghosting problem on the list, since is not exactly performant to do this on the fronted we will need 2 new fields on the list endpoint: office_label and section_label (be sure that the label in any case -if selected- ) please do not remove office and section ( the ones with ID ) for compatibility reasons

**Comment by lordfuoco** [comment]
@kasfaw @torbent @anusenan @janpanchalingam1 me and @ilcsik double checked this, this is not a ghosting issue, it's a data issue, the trips showing N.A. are trips which do not have a section or an office associated, this can happen in 2 cases: 

1. the trip is saved without it ( and it's in status Planned which ignore the required fields)
2. the trip was migrated from the previous software and it does not contain that info

At this point we are not sure of the action to do, do we remove N.A.  and we put empty string in this 2 cases ? or no action is to be performed and N.A. is a good placeholder for the 'missing' data ?

**Comment by anusenan** [comment]
@lordfuoco  from the screenshot - its clear these are more recent trips so point 2 may not be the cause. We need to check point 1 though. @kasfaw what do you say?

**Comment by lordfuoco** [comment]
@anusenan the screenshot contains data that is not present at the moment in staging so I can't verify directly these reference numbers, but for sure no trip can move from status Planned without the required data. 

I found trips in staging which do show the problem of a migrated trip : https://etools-staging.unicef.org/t2f/travel-list?reverse=true&page=1&page_size=10&search&sort_by=id&show_hidden=false&f_traveler=7
( workspace Kyrgyzstan ) 

The section is empty because it's not present in the data ( also empty in the detail page ) 

So let's not exclude type 2 as a reason for the N.A. to appear. Also it would be nice to know where this problem was found: old version of staging or production ?

**Comment by anusenan** [comment]
@janpanchalingam1  can you update this ticket addressing the above question?

**Comment by janpanchalingam1** [comment]
@lordfuoco this was happening in production and staging. After retesting, it is only occuring in migrated trips where offices or sections may have been removed. We can move this card to closed as it has been fixed in staging when tested in IE and Chrome.

**Comment by lordfuoco** [comment]
@janpanchalingam1 @torbent thank you for validating it, will you move the card ?
