### ISSUE TITLE
Intervention details pages 'edit mode' - Issues

### ISSUE THREAD

**Issue by adi130987** [unicef/etools-issues#344]
Edit mode is not working as it should on interventions pages.
Steps to reproduce:
* open a PD details  page where you have write permissions => fields can be edited
* refresh browser page => all fields are readonly even you have permissions to change fields

**Comment by roxanavlad** [comment]
@adi130987 , the issue is fixed

but i found a new issue with the refresh in the edit mode: the PD details page isn't displayed anymore after I try 2 types of refresh

steps to reproduce the issue:
1. go to PD/SSFA ToR and select a PD
2. the fields can be edited
3. select refresh from the browser
4. the detail page is refreshed and all the data is displayed, fields can be edited
5. select refresh from the application (the refresh button from the right corner, next to the sign out button)
6. select PD/SSFA ToR to be refreshed
7. select refresh data button

Expected result: the detail page is refreshed and the data is displayed

Actual result: the detail page is refreshed and the user is redirected to the intervention list, which is empty. 
I believe that this due to the fact that the app refresh works as a clear cached, as described in this issue: https://github.com/unicef/etools-issues/issues/250
This flow is not good for the UX, as it can lead the user to believe that there is no data in the intervention list, or that the data that he/she was editing got lost.
