### ISSUE TITLE
Non-TA Workflow: No Email Notification to Supervisor

### ISSUE THREAD

**Issue by janpanchalingam1** [unicef/etools-issues#390]
Browser: Chrome and IE
Workspace: Sierra Leone and Lebanon
1) Plan a Non-TA trip
2) Submit to Supervisor for Approval
3) Supervisor does not receive email notification for the required approval

**Comment by ilcsik** [comment]
@janpanchalingam1 

Is this a permanent error that you can reproduce, or happens occasionally?

I tested this with puli test accounts, Sierra Leone and Kyrgyzstan on the Dev server, and I can see the emails being sent (there's a list on the admin site) so the logic should be ok.

 However, the one that we tried with Nik's inbox did not get delivered.  We don't know anything about the email configuration on the Dev server, so @ntrncic is going to check if it's turned on and then we go from there.

**Comment by janpanchalingam1** [comment]
@ilcsik @ntrncic this is a permanent error. I have replicated this in staging and this is reported by users in production.

**Comment by ilcsik** [comment]
@janpanchalingam1 thank you! I assume it does not depend on workspace, you just happen to test these two?

**Comment by janpanchalingam1** [comment]
@ilcsik yes, it does not depend on workspace but otherwise all other emails are arriving in order

**Comment by ilcsik** [comment]
@janpanchalingam1 @ntrncic so to sum up this card I did test this and I can see that the send_mail() method is reached and I can see the email entry that says that the email is sent. But I cannot investigate any further since I don't have access to the actual email sending environment on your dev and staging, nor can I setup on our dev since email server credentials are of course not to be shared with us.

Can you please check email settings on staging, and/or check logs if there's any exception thrown  by your email infrastructure when sending email?

**Comment by janpanchalingam1** [comment]
Thanks @ilcsik, @ntrncic are you able to check this?

**Comment by torbent** [comment]
@robertavram @ntrncic I understand that this is related to a celery issue? Please move this card along when fixed.

**Comment by ntrncic** [comment]
this has been fixed as we restarted celery worker

**Comment by janpanchalingam1** [comment]
Pass
