### ISSUE TITLE
Non-TA workflow: Supervisor Notification Workflow

### ISSUE THREAD

**Issue by janpanchalingam1** [unicef/etools-issues#399]

**Comment by janpanchalingam1** [comment]
All browsers and workspaces:

1) Traveller creates a non-TA trip
2) Traveller clicks 'Save & Submit'
3) Pop up question asks 'Do you require a supervisor approval for trip?'
4) Traveller selects 'Continue without Approval' and 'Only Save'
5) Then to complete trip the Traveller clicks 'Save & Submit'
6) Pop up question 'Do you require a supervisor approval for trip?'  shows again and traveller can finalize in pop up box 'Is this trip report final?'

The behaviour on step 6 should go directly to pop-up 'Is this trip report final?'

**Comment by lordfuoco** [comment]
@janpanchalingam1 @kasfaw this is the flow that we discussed on the initial call I think. Because to avoid having again the question ' 'Do you require a supervisor approval for trip? ' we would need another state that we don't have.

We would need to introduce a new state, create a p-matrix for it and transaction and retest the whole system.

As far as I can remember the goal here was to keep it simple,  to avoid drastic changes here.
Maybe we can discuss this 'face' to ' 'face' on the meeting this afternoon.
