### ISSUE TITLE
Unresponsive Page for India Workspace in Staging

### ISSUE THREAD

**Issue by janpanchalingam1** [unicef/etools-issues#437]

**Comment by janpanchalingam1** [comment]
Browser: IE and Chrome
Workspace: India
Environment: Staging

Experiencing unresponsive page pop up in Chrome and IE while in India workspace:
![image](https://user-images.githubusercontent.com/26144740/27091328-d2a08bea-502d-11e7-82f6-6a7d74ad805e.png)

**Comment by anusenan** [comment]
Hey @torbent can you check why this is happening for this particular workspace?

**Comment by torbent** [comment]
@ntrncic @robertavram @ewheeler @anusenan . I have isolated this to be caused by https://etools-staging.unicef.org/api/wbs_grants_funds/ that takes several minutes to get back, and occupies the whole DB on staging for that period of time.
The approach until now has been that we build the JSON on the backend, and feeds it to the front end who then does a simple lookup in the JSON for how to populate the dropdowns. More work for backend in less calls ( this has been a guiding principle )... But in India there is an extreme about of WBS, grants and funds compared to the rest of the countries. Currently we're prefetching this, which turns out to be very expensive in this scenario. 

@simon-the-sloth is currently trying to optimise on this call and can probably improve this with 50-75% by optimising this for this "data balance".

The correct solution ( in our opinion ) would be to only send one list up at the time, and let the front end ajax call for the next list based on previous selection, this would  dramatically decrease the impact on the time spend in DB, but this practice would be going against some fundamental guidelines for how we feed data to the frontend. @ewheeler @robertavram @ntrncic let us know if we should abandon this principle and move forward on this task.

**Comment by simon-the-sloth** [comment]
Did some speed improvements. Now the endpoint should be significantly faster. But still the frontend has to be tested to see if it can handle the amount of data.

**Comment by robertavram** [comment]
@simon-the-sloth, on top of your improvements etag caching could be a good solution.

**Comment by janpanchalingam1** [comment]
@simon-the-sloth this error is showing in multiple workspaces (Sudan, Jordan, Philippines). Will this be fixed for all workspaces?

**Comment by torbent** [comment]
@janpanchalingam1 is it still an issue for India?

**Comment by janpanchalingam1** [comment]
@torbent yes, India, Sudan, Jordan, Philippines (of the ones we have been testing in)

**Comment by simon-the-sloth** [comment]
@robertavram Can you please give us a DB dump from DEV? There is an error what I cannot reproduce with my current dump locally.
