### ISSUE TITLE
IE: Different number of partners display in Chrome vs. IE

### ISSUE THREAD

**Issue by mpawlowski85** [unicef/etools-issues#497]
Workspace: Nigeria
Steps to reproduce: 
1. Go to PMP and select Show Hidden 
2. See how many partners are displayed. 

Result in IE: 731
Result in Chrome: 933

**Comment by mpawlowski85** [comment]
![image](https://user-images.githubusercontent.com/26120371/27639834-78186850-5be5-11e7-82b6-2b6d71c6bdd2.png)

![image](https://user-images.githubusercontent.com/26120371/27639896-b492d8f6-5be5-11e7-8552-82cd6265cd23.png)

**Comment by janpanchalingam1** [comment]
Tested in production and in staging on August 8 and this is still an issue

**Comment by janpanchalingam1** [comment]
![image](https://user-images.githubusercontent.com/26144740/29085956-eceeeb44-7c3e-11e7-8bbb-b5c69568ab0e.png)

**Comment by daniel-tabarcea** [comment]
I've done some research on the issue and here's what I've found: 
The missing partners are ones witch do not have a name. There is a limitation in the Dexie library on certain browsers that removes records having an empty value of the property we order by from the results set. By default the partners are ordered by name, so entries with empty names are being ignored in ie11. When sorting by reference number for example, all the missing records reappear.
I can add placeholders instead of empty names to work around this limitation but it requires a fair bit of the work to etools-ajax and i want to make sure it's actually worth it.  At the moment I can't see a situation in witch partners can not have names, and the troublesome records seem to only have ref numbers. 
@robertavram @ntrncic What are your thoughts on this?

**Comment by daniel-tabarcea** [comment]
@ntrncic @robertavram is this issue still relevant?  i think it's out of its place in needs review, maybe we should move it to the backlog
