### ISSUE TITLE
Trip itinerary

### ISSUE THREAD

**Issue by janpanchalingam1** [unicef/etools-issues#541]
1) User creates a new trip and begins to enter information in itinerary
2) User deletes itinerary information
3) User clicks 'save' or 'save and submit' and is unable to move forward unless trip is filled out

User should be able to delete itinerary information and 'save' or 'save and submit' trip.

**Comment by ewheeler** [comment]
@janpanchalingam1 what is the expected behavior here? this is what i would expect to happen as etools' validation will not let the trip save with invalid info.. and a trip must have at least two itinerary items in order to be valid

if you enter 3 itinerary items, for example, you can delete one and still save or save/submit. so there doesn't seem to be any bug here

this would necessitate a change to the business requirements/validation in order to allow invalid trips to be saved

**Comment by janpanchalingam1** [comment]
@ewheeler yes you are correct - you need 2 valid entries to save the itinerary. If a user would like to create a trip without itinerary information, they are able to save and submit it (expected behaviour). The issue here is that if you want to remove the itinerary and save without any itinerary information, it does not allow you to save if it has been entered and then removed in the planned stage.

**Comment by ewheeler** [comment]
@janpanchalingam1 ok i see. so if a user intends to just create a draft trip without itinerary items then everything works

this issue seems like a very rare edge case and probably not worth fixing. if a user intends to draft a trip and has enough detail to fill in overview, activities, etc then they can just put in some provisional details into itinerary in order to save the draft

**Comment by ShrinivasPuranik** [comment]
Note: Partial entry or blank entry, still not permitted.
Monitor the incidence of user behaviour based on change in text to optional

**Comment by ewheeler** [comment]
see also 
https://github.com/unicef/etools-issues/issues/633
https://github.com/unicef/etools-issues/issues/634

**Comment by ntrncic** [comment]
we have updated the trip form to have the itinerary section collapsed. This makes it harder for the user to enter data into that section, if the user starts entering itinerary data then they will have to enter it correctly and are not allowed to delete. 

To change the validation and allow users to delete entered itineraries will take one week of developer time. At this moment will move to closed and see if it becomes a problem again with users.
