### ISSUE TITLE
(UAT) Display of asterisk mark for CP Structure

### ISSUE THREAD

**Issue by KKaselkar** [unicef/etools-issues#766]
Standardize the display of asterisk marks for mandatory fields for agreement type, partner name, CP structure. Currently asterisk is removed from CP structure after selecting the value, request to display the asterisk back.

**Comment by adi130987** [comment]
@KKaselkar please provide more details: steps to reproduce, used browser, environment you tested on, current country, screenshots or any other detail you consider useful.

**Comment by KKaselkar** [comment]
On chrome browser, work space is Pakistan
![image.png](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/59c925e34d3dcd001231c900/125516c66e82c728ace21e0d46e1999b2487c1e5cdf9ad4cae58f3806b1c65267106f47f2181b57abb177856570b4fac400a5712adfa8839baa47e21d40854b088270a36d43703adb1881eba01bc268a4d8cb1ba8b44c6fa70.png)

**Comment by adi130987** [comment]
@KKaselkar the CP Structure is not a required field when the PD/SSFA is draft. From the moment PD/SSFA status changes to signed then this field will have the asterisk on it because in this status the field is required.

But, we might have an issue here regarding this field. The PMP Redesign specs are are saying this field  should be locked and not editable even using amendments: 

`When the PD status changed to “Signed” the field “CP Structure” will be permanently locked. It will not be possible to change it even through an amendment. It will also not be possible to have a single PD contribute to two CP structures.`

and in amendments section:

`Message 1 appears: “All fields in the details tab will now be open for editing. Please change all necessary fields before hitting save”... After user selects ok, then all fields in the details tab will open for editing.`.  

Right now, `CP Strucure` can be edited through an amendment.

@mpawlowski85 can you please clarify this? Should this field editable through an amendment? Thanks.

**Comment by mpawlowski85** [comment]
@adi130987 
SO you should be able to amend it with an amendment. 
The issue is that now if you add an amendment and select a different CP structure, the CP outputs related to the Old CP Structure disappear. Is there something we can do about that?

**Comment by adi130987** [comment]
@mpawlowski85 yes, you can use an amendment to change the CP Structure. 
Regarding the issue you described, we could make changes on frontend to keep showing the previous CP outputs selected, but first we need to know if the CP Structure can be changed using amendments.

**Comment by mpawlowski85** [comment]
@adi130987 Sorry - I was not clear - Yes you must be able to change CP Structure using amendments.

**Comment by adi130987** [comment]
@mpawlowski85 ok... @daniel-tabarcea is making some frontend changes for this, so the cp outputs previously selected.

**Comment by mpawlowski85** [comment]
@adi130987 cheers!

**Comment by mpawlowski85** [comment]
@mpawlowski85 - split into two cards

**Comment by robertavram** [comment]
@adi130987 please don;t get started on this yet... I will clarify with you

**Comment by adi130987** [comment]
@robertavram we found a bug related to this in our custom dropdown element that needs to be fixed asap, in the missing option functionality (ghost data).
