### ISSUE TITLE
Identify location type in parenthesis beside location

### ISSUE THREAD

**Issue by anusenan** [unicef/etools-issues#78]

**Comment by anusenan** [comment]
![image](https://cloud.githubusercontent.com/assets/25492170/23725084/31352dee-041d-11e7-80bf-dd2694786d7d.png)

**Comment by ntrncic** [comment]
@anusenan where do they want this added?

**Comment by anusenan** [comment]
@janpanchalingam1 - can you address this?

**Comment by janpanchalingam1** [comment]
![locations](https://cloud.githubusercontent.com/assets/26144740/23921027/70bae0ac-08d3-11e7-8f01-403477991b76.png)

If possible, could the location type be in brackets beside the location? As you can see, there are multiple Aabba for example but it is because one is a 'village' and another is a 'social development center' so it could show as Aabba (Village) and Aabba (Social Development Center)

**Comment by torbent** [comment]
Endpoint should send up:
<Location Name> ( <Location Type> - <Pcode> )

**Comment by janpanchalingam1** [comment]
Update from Budapest Meeting: to display "location (location type - P Code)"

**Comment by kasfaw** [comment]
@torbent undertand that you will let us know if you need any additional information on this one?

**Comment by janpanchalingam1** [comment]
Pass
