### ISSUE TITLE
HACT Dash - Add Flag for missing assessment

### ISSUE THREAD

**Issue by janpanchalingam1** [unicef/etools-issues#944]
Field 1.1.6a: Flag for missing assessment – display when: 
1) field 1.1.4 = micro assessment AND no micro assessment is attached or completed; OR 
2) if field 1.1.4 = audit results AND no final report has been submitted for the audit in the Auditor Portal
![image](https://user-images.githubusercontent.com/26144740/33282414-97436172-d376-11e7-88fd-7c875bb5b072.png)

Specifications can be found here: https://unicef.sharepoint.com/teams/OED/eTools/_layouts/15/guestaccess.aspx?guestaccesstoken=ICrnaIDkFYXzOtFchO%2bbBgkOK6XB0OD%2bX7pUaU230uE%3d&docid=2_1ad64d07b71f4493189770c448f472dbe&rev=1

**Comment by evrimm** [comment]
See: https://projects.invisionapp.com/share/XEE9IC02V#/screens/264610277
Tooltip should read: "Micro assessment or audit report has not been submitted through the Auditor Portal" (mock up is not the same) IS it possible to wrap the text within tooltip since it's very long?
Icon: warning at 16 x 16 px

**Comment by domdinicola** [comment]
@janpanchalingam1 which is the default for other type of assessment?

**Comment by domdinicola** [comment]
@janpanchalingam1 I will need your help to get info to retrieve the Micro assessment abd how to get info from Auditor Portal

**Comment by janpanchalingam1** [comment]
No longer a business requirement. Removing from waffle.
