### ISSUE TITLE
Start Data and End Date should auto populate

### ISSUE THREAD

**Issue by anusenan** [unicef/etools-issues#97]
Explanation: Redudancy on the date: could the system use date from trip plan to itinerary and activities - dates are entered 3 times - which is a bit exhaustive. What if we only leave 1 day? It will be difficult to convince our users to add dates 3 times

**Comment by evrimm** [comment]
@kasfaw @janpanchalingam1  I am about to create a test scenario for this card since it looks like it might go into staging this week. This request needs more clarification. Although I agree that entering dates 3 times is exhaustive, auto populating comes with its own potential issues, concerns are:

Start Date will populate Date of Visit? Which doesn't make sense because the day you depart might not be the day of the visit. 

End date will populate Departure Date of the 2nd leg of Itinerary ? But the 2nd leg of itinerary doesn't even show by default.

**Comment by janpanchalingam1** [comment]
@evrimm I think the intention was that the start date would be date of departure (itinerary). Yes, you are right. I was hoping that the second leg would first show, and if shown would have end date so I am not sure how this will look by design. I think we need to discuss what makes the most sense with Slavi since he is now the business owner and has a lot of suggested changes.

**Comment by aldohunicef** [comment]
![image](https://cloud.githubusercontent.com/assets/26142645/24962445/f8a53862-1f69-11e7-841b-b0bec3f36a80.png)

**Comment by janpanchalingam1** [comment]
As seen in the above screen shot, start and end dates auto populate when date of visit and itinerary are entered. The Start and End date should be locked until a date is entered in Itinerary for TA. For non-ta trip and international trip should be editable.

**Comment by janpanchalingam1** [comment]
As seen above, trip activities are updating start and end date as well as itinerary is updating start and end date. All testers have agreed to make all fields editable - no autopoplate.
